//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanVe
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYENBAY
    {
        public string MACB { get; set; }
        public string MASBDI { get; set; }
        public string MASBDEN { get; set; }
        public string MAHHK { get; set; }
        public Nullable<int> THOIGIANBAY { get; set; }
        public Nullable<int> SOGHEHANG1 { get; set; }
        public Nullable<int> SOGHEHANG2 { get; set; }
        public Nullable<int> GIAVE { get; set; }
    }
}
